/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author david
 */
public class JFPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFPrincipal
     */
    public JFPrincipal() {
        initComponents();
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setVisible(true);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lbNombre = new javax.swing.JLabel();
        lbImg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pCompra = new javax.swing.JPanel();
        lbcompra = new javax.swing.JLabel();
        pInventario = new javax.swing.JPanel();
        lbInventario = new javax.swing.JLabel();
        pVenta = new javax.swing.JPanel();
        lbVenta = new javax.swing.JLabel();
        pAsistencia = new javax.swing.JPanel();
        lbAsistencia = new javax.swing.JLabel();
        pBalance = new javax.swing.JPanel();
        lbBalance = new javax.swing.JLabel();
        pFunciones = new javax.swing.JPanel();
        lbFunciones = new javax.swing.JLabel();
        pPersistir = new javax.swing.JPanel();
        lbPersistir = new javax.swing.JLabel();
        lbtt1 = new javax.swing.JLabel();
        lbtt2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(232, 112, 36));

        jPanel5.setBackground(new java.awt.Color(232, 112, 36));
        jPanel5.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(), javax.swing.BorderFactory.createCompoundBorder()));

        lbNombre.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        lbNombre.setForeground(new java.awt.Color(0, 0, 0));
        lbNombre.setText("La Góndola");

        lbImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbImg, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbImg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 112, 36)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 112, 36))));

        pCompra.setBackground(new java.awt.Color(255, 255, 255));
        pCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pCompraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pCompraMouseExited(evt);
            }
        });

        lbcompra.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        lbcompra.setForeground(java.awt.Color.black);
        lbcompra.setText("Registrar Compra ");
        lbcompra.setPreferredSize(new java.awt.Dimension(119, 38));

        javax.swing.GroupLayout pCompraLayout = new javax.swing.GroupLayout(pCompra);
        pCompra.setLayout(pCompraLayout);
        pCompraLayout.setHorizontalGroup(
            pCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbcompra, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pCompraLayout.setVerticalGroup(
            pCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCompraLayout.createSequentialGroup()
                .addComponent(lbcompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pInventario.setBackground(new java.awt.Color(255, 255, 255));
        pInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pInventario.setMaximumSize(new java.awt.Dimension(181, 19));
        pInventario.setPreferredSize(new java.awt.Dimension(119, 38));
        pInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pInventarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pInventarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pInventarioMouseExited(evt);
            }
        });

        lbInventario.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        lbInventario.setForeground(new java.awt.Color(0, 0, 0));
        lbInventario.setText("Inventario");

        javax.swing.GroupLayout pInventarioLayout = new javax.swing.GroupLayout(pInventario);
        pInventario.setLayout(pInventarioLayout);
        pInventarioLayout.setHorizontalGroup(
            pInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbInventario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pInventarioLayout.setVerticalGroup(
            pInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbInventario)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pVenta.setBackground(new java.awt.Color(255, 255, 255));
        pVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pVenta.setPreferredSize(new java.awt.Dimension(119, 38));
        pVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pVentaMouseExited(evt);
            }
        });

        lbVenta.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        lbVenta.setForeground(new java.awt.Color(0, 0, 0));
        lbVenta.setText("Registrar venta");

        javax.swing.GroupLayout pVentaLayout = new javax.swing.GroupLayout(pVenta);
        pVenta.setLayout(pVentaLayout);
        pVentaLayout.setHorizontalGroup(
            pVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbVenta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pVentaLayout.setVerticalGroup(
            pVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbVenta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pAsistencia.setBackground(new java.awt.Color(255, 255, 255));
        pAsistencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pAsistencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pAsistenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pAsistenciaMouseExited(evt);
            }
        });

        lbAsistencia.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        lbAsistencia.setForeground(java.awt.Color.black);
        lbAsistencia.setText("Registrar Asistencia");
        lbAsistencia.setPreferredSize(new java.awt.Dimension(119, 38));

        javax.swing.GroupLayout pAsistenciaLayout = new javax.swing.GroupLayout(pAsistencia);
        pAsistencia.setLayout(pAsistenciaLayout);
        pAsistenciaLayout.setHorizontalGroup(
            pAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAsistenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pAsistenciaLayout.setVerticalGroup(
            pAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAsistenciaLayout.createSequentialGroup()
                .addComponent(lbAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pBalance.setBackground(new java.awt.Color(255, 255, 255));
        pBalance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pBalance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pBalanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pBalanceMouseExited(evt);
            }
        });

        lbBalance.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        lbBalance.setForeground(java.awt.Color.black);
        lbBalance.setText("Opciones de Balance");
        lbBalance.setPreferredSize(new java.awt.Dimension(119, 38));

        javax.swing.GroupLayout pBalanceLayout = new javax.swing.GroupLayout(pBalance);
        pBalance.setLayout(pBalanceLayout);
        pBalanceLayout.setHorizontalGroup(
            pBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBalanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pBalanceLayout.setVerticalGroup(
            pBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBalanceLayout.createSequentialGroup()
                .addComponent(lbBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pFunciones.setBackground(new java.awt.Color(255, 255, 255));
        pFunciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pFunciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pFuncionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pFuncionesMouseExited(evt);
            }
        });

        lbFunciones.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        lbFunciones.setForeground(java.awt.Color.black);
        lbFunciones.setText("Funciones Especiales (Admin)");
        lbFunciones.setPreferredSize(new java.awt.Dimension(119, 38));

        javax.swing.GroupLayout pFuncionesLayout = new javax.swing.GroupLayout(pFunciones);
        pFunciones.setLayout(pFuncionesLayout);
        pFuncionesLayout.setHorizontalGroup(
            pFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFuncionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pFuncionesLayout.setVerticalGroup(
            pFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFuncionesLayout.createSequentialGroup()
                .addComponent(lbFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pPersistir.setBackground(new java.awt.Color(255, 255, 255));
        pPersistir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pPersistir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pPersistirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pPersistirMouseExited(evt);
            }
        });

        lbPersistir.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        lbPersistir.setForeground(java.awt.Color.black);
        lbPersistir.setText("Persistir Información");
        lbPersistir.setPreferredSize(new java.awt.Dimension(119, 38));

        javax.swing.GroupLayout pPersistirLayout = new javax.swing.GroupLayout(pPersistir);
        pPersistir.setLayout(pPersistirLayout);
        pPersistirLayout.setHorizontalGroup(
            pPersistirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPersistirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPersistir, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pPersistirLayout.setVerticalGroup(
            pPersistirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPersistirLayout.createSequentialGroup()
                .addComponent(lbPersistir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pInventario, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
            .addComponent(pVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
            .addComponent(pCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pAsistencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pBalance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pFunciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pPersistir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pPersistir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(396, Short.MAX_VALUE))
        );

        lbtt1.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        lbtt1.setForeground(new java.awt.Color(0, 0, 0));
        lbtt1.setText("Restaurante : La góndola ");

        lbtt2.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        lbtt2.setForeground(new java.awt.Color(0, 0, 0));
        lbtt2.setText("Sistema de Contabilidad");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbtt1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbtt2))
                        .addContainerGap(231, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(lbtt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbtt2)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public Font font = new Font("Lucida Console", Font.BOLD, 18);
    public Font font2 = new Font("Lucida Console", Font.PLAIN, 18);
    
    private void pCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCompraMouseEntered
        this.pCompra.setBackground(new Color(232,112,36));
        this.lbcompra.setForeground(Color.white);
        this.lbcompra.setFont(font);
    }//GEN-LAST:event_pCompraMouseEntered

    private void pCompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCompraMouseExited
        this.pCompra.setBackground(Color.white);
        this.lbcompra.setForeground(Color.black);
        this.lbcompra.setFont(font2);
    }//GEN-LAST:event_pCompraMouseExited

    private void pInventarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pInventarioMouseEntered
        this.pInventario.setBackground(new Color(232,112,36));
        this.lbInventario.setForeground(Color.white);
        this.lbInventario.setFont(font);
    }//GEN-LAST:event_pInventarioMouseEntered

    private void pInventarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pInventarioMouseExited
        this.pInventario.setBackground(Color.white);
         this.lbInventario.setForeground(Color.black);
        this.lbInventario.setFont(font2);
    }//GEN-LAST:event_pInventarioMouseExited

    private void pVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pVentaMouseEntered
        this.pVenta.setBackground(new Color(232,112,36));
        this.lbVenta.setForeground(Color.white);
        this.lbVenta.setFont(font);
    }//GEN-LAST:event_pVentaMouseEntered

    private void pVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pVentaMouseExited
        this.pVenta.setBackground(Color.white);
        this.lbVenta.setForeground(Color.black);
        this.lbVenta.setFont(font2);
    }//GEN-LAST:event_pVentaMouseExited

    private void pAsistenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pAsistenciaMouseEntered
        this.pAsistencia.setBackground(new Color(232,112,36));
        this.lbAsistencia.setForeground(Color.white);
        this.lbAsistencia.setFont(font);
    }//GEN-LAST:event_pAsistenciaMouseEntered

    private void pAsistenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pAsistenciaMouseExited
        this.pAsistencia.setBackground(Color.WHITE);
        this.lbAsistencia.setForeground(Color.black);
        this.lbAsistencia.setFont(font2);
    }//GEN-LAST:event_pAsistenciaMouseExited

    private void pBalanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pBalanceMouseEntered
        this.pBalance.setBackground(new Color(232,112,36));
        this.lbBalance.setForeground(Color.white);
        this.lbBalance.setFont(font);
    }//GEN-LAST:event_pBalanceMouseEntered

    private void pBalanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pBalanceMouseExited
        this.pBalance.setBackground(Color.white);
         this.lbBalance.setForeground(Color.black);
        this.lbBalance.setFont(font2);
    }//GEN-LAST:event_pBalanceMouseExited

    private void pFuncionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pFuncionesMouseEntered
        this.pFunciones.setBackground(new Color(232,112,36));
        this.lbFunciones.setForeground(Color.white);
        this.lbFunciones.setFont(font);
    }//GEN-LAST:event_pFuncionesMouseEntered

    private void pFuncionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pFuncionesMouseExited
        this.pFunciones.setBackground(Color.WHITE);
        this.lbFunciones.setForeground(Color.black);
        this.lbFunciones.setFont(font2);
    }//GEN-LAST:event_pFuncionesMouseExited

    private void pPersistirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pPersistirMouseEntered
        this.pPersistir.setBackground(new Color(232,112,36));
        this.lbPersistir.setForeground(Color.white);
        this.lbPersistir.setFont(font);
    }//GEN-LAST:event_pPersistirMouseEntered

    private void pPersistirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pPersistirMouseExited
        this.pPersistir.setBackground(Color.white);
        this.lbPersistir.setForeground(Color.black);
        this.lbPersistir.setFont(font2);
    }//GEN-LAST:event_pPersistirMouseExited

    private void pInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pInventarioMouseClicked
        JOptionPane.showConfirmDialog(null, "Undeveloped Function", "Funciona",  JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_pInventarioMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new JFPrincipal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbAsistencia;
    private javax.swing.JLabel lbBalance;
    private javax.swing.JLabel lbFunciones;
    private javax.swing.JLabel lbImg;
    private javax.swing.JLabel lbInventario;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbPersistir;
    private javax.swing.JLabel lbVenta;
    private javax.swing.JLabel lbcompra;
    private javax.swing.JLabel lbtt1;
    private javax.swing.JLabel lbtt2;
    private javax.swing.JPanel pAsistencia;
    private javax.swing.JPanel pBalance;
    private javax.swing.JPanel pCompra;
    private javax.swing.JPanel pFunciones;
    private javax.swing.JPanel pInventario;
    private javax.swing.JPanel pPersistir;
    private javax.swing.JPanel pVenta;
    // End of variables declaration//GEN-END:variables
}
